### ISSUE TITLE
Mime Error

### ISSUE THREAD

**Issue by Kawser-nerd** [jeanralphaviles/comment_parser#2]
At the time of running your tool with one of my script files, I faced the following error:
AttributeError: 'str' object has no attribute 'decode'

If I remove decode, I again saw the following error:
comment_parser.comment_parser.UnsupportedError: Unsupported MIME type

I am using python 3.5.2

**Comment by jeanralphaviles** [comment]
You chopped some of the output of the error message there. What was the MIME type of the file you were trying to parse? It may have not been supported.
