### ISSUE TITLE
c++ extraction fails

### ISSUE THREAD

**Issue by joky27** [jeanralphaviles/comment_parser#6]
Hi！When I tried this tool to extract c++ comments  from the attached file,it only extracted 9 comments.Obviously,there are more than 9 comments....
[Expression.txt](https://github.com/jeanralphaviles/comment_parser/files/2686340/Expression.txt)

**Comment by jeanralphaviles** [comment]
I've ran your test file through comment_parser and spot checked some comments, it seemed to do the right thing.

The library also extracted 104 comments. Were you setting the MIME field in your call to _extract_comments_ to something that was not C++?

```python
>>> from comment_parser import comment_parser
>>> len(comment_parser.extract_comments('/tmp/Expression.txt'))
104
```
