### ISSUE TITLE
C# Support

### ISSUE THREAD

**Issue by estebanborai** [jeanralphaviles/comment_parser#7]
Hey,

Is there any support for C# in mind? I'm looking into processing some C# and JavaScript files in order to create some documentation.

If you don't mind I would like to help.

Thanks in advance!

**Comment by jeanralphaviles** [comment]
C# comments look to be the same style as C++. I can add C# to use the same C++ parser.

Do you need any special treating of XML-style comments?

**Comment by estebanborai** [comment]
I don't think so!
If I'm able to get the comments as strings that will be good enough!

**Comment by jeanralphaviles** [comment]
I haven't been able to find any MIME types specific to C#. From what I can tell, libmagic will interpret sources as C++ and should parse just fine.

Here I've used a [C# Game of Life code snippet](https://gist.github.com/joelmartinez/1194013) to show that C# works.

```python
>>> import magic
>>> magic.from_file('/tmp/GameOfLife.cs')                                                                                      
'C++ source, ASCII text'
>>> from comment_parser import comment_parser  
>>> print([c.text() for c in comment_parser.extract_comments('/tmp/GameOfLife.cs')])
[' when a generation has completed', ' now flip the back buffer so we can start processing on the next generation', " begin the next generation's processing asynchronously", ' only begin the generation if the previous process was completed', ' zombification', ' initialize with a blinker']                                                                                                                     
```
